//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class leerhulpEntities : DbContext
    {
        public leerhulpEntities()
            : base("name=leerhulpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aanvullendeInfo> aanvullendeInfo { get; set; }
        public virtual DbSet<caputs> caputs { get; set; }
        public virtual DbSet<vertalingen> vertalingen { get; set; }
        public virtual DbSet<woorden> woorden { get; set; }
    }
}
