//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vertalingen
    {
        public int id { get; set; }
        public string term { get; set; }
        public int woordId { get; set; }
    
        public virtual woorden woorden { get; set; }
    }
}
